// Publishes the gate-3-validated strategy doc as a Confluence page.
// Deterministic code owns the page structure; the AI only wrote the prose
// that already passed the gate. Created ticket keys are linked into the
// action plan so the doc and the board reference each other.
const api = require("@forge/api");
const { route } = api;

async function createStrategyPage({ doc, meeting, createdTickets, jobId }) {
  const spaceKey = process.env.CONFLUENCE_SPACE_KEY;
  if (!spaceKey) {
    throw new Error("CONFLUENCE_SPACE_KEY not set (forge variables set CONFLUENCE_SPACE_KEY <key>)");
  }

  const body = {
    type: "page",
    title: `${doc.title} (${meeting.date || new Date().toISOString().slice(0, 10)})`,
    space: { key: spaceKey },
    body: {
      storage: {
        value: renderStorageFormat({ doc, meeting, createdTickets, jobId }),
        representation: "storage",
      },
    },
  };

  const response = await api.asApp().requestConfluence(route`/wiki/rest/api/content`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });

  if (!response.ok) {
    const errorBody = await response.text();
    throw new Error(`Confluence API ${response.status}: ${errorBody}`);
  }

  const result = await response.json();
  const pageUrl = `${result._links?.base || "/wiki"}${result._links?.webui || ""}`;
  console.log(`[Confluence] Created strategy page ${result.id}: ${doc.title}`);
  return { pageId: result.id, pageUrl, title: body.title };
}

// Confluence storage format is XHTML. Everything AI-written passes through
// esc(), the gate validated substance, this guards markup.
function renderStorageFormat({ doc, meeting, createdTickets, jobId }) {
  const parts = [];

  parts.push(
    `<ac:structured-macro ac:name="info"><ac:rich-text-body><p>` +
      `Generated by meeting-pipeline from <strong>${esc(meeting.meetingTitle)}</strong>` +
      `${meeting.date ? ` (${esc(meeting.date)})` : ""}` +
      `${meeting.attendees?.length ? `, attendees: ${esc(meeting.attendees.join(", "))}` : ""}.` +
      `${meeting.loomUrl ? ` <a href="${esc(meeting.loomUrl)}">Source recording</a>.` : ""}` +
      ` This is a synthesized strategy document, not a transcript.</p></ac:rich-text-body></ac:structured-macro>`
  );

  parts.push(`<h2>Executive summary</h2>`);
  parts.push(paragraphs(doc.executive_summary));

  parts.push(`<h2>Context</h2>`);
  parts.push(paragraphs(doc.context));

  parts.push(`<h2>Decisions</h2>`);
  for (const d of doc.decisions) {
    parts.push(`<h3>${esc(d.decision)}</h3>`);
    parts.push(`<p><strong>Why:</strong> ${esc(d.rationale)}</p>`);
    if (d.dissent) {
      parts.push(
        `<ac:structured-macro ac:name="note"><ac:rich-text-body><p>` +
          `<strong>Recorded dissent:</strong> ${esc(d.dissent)}</p></ac:rich-text-body></ac:structured-macro>`
      );
    }
  }

  parts.push(`<h2>Action plan</h2>`);
  parts.push(paragraphs(doc.action_plan));
  if (createdTickets.length > 0) {
    parts.push(`<p><strong>Tracked in Jira:</strong></p><ul>`);
    for (const t of createdTickets) {
      // The Jira macro renders a live issue card, status included.
      parts.push(
        `<li><ac:structured-macro ac:name="jira">` +
          `<ac:parameter ac:name="key">${esc(t.issueKey)}</ac:parameter>` +
          `</ac:structured-macro> ${esc(t.summary || "")}</li>`
      );
    }
    parts.push(`</ul>`);
  }

  if (doc.risks_and_open_questions.length > 0) {
    parts.push(`<h2>Risks &amp; open questions</h2><ul>`);
    for (const r of doc.risks_and_open_questions) parts.push(`<li>${esc(r)}</li>`);
    parts.push(`</ul>`);
  }

  if (doc.explicitly_deferred.length > 0) {
    parts.push(`<h2>Explicitly deferred</h2>`);
    parts.push(`<p>Recorded so the same debate does not restart next month:</p><ul>`);
    for (const d of doc.explicitly_deferred) parts.push(`<li>${esc(d)}</li>`);
    parts.push(`</ul>`);
  }

  parts.push(`<hr/><p><em>Pipeline job: ${esc(jobId)}</em></p>`);
  return parts.join("\n");
}

function paragraphs(text) {
  return text
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => `<p>${esc(p)}</p>`)
    .join("\n");
}

function esc(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

module.exports = { createStrategyPage, renderStorageFormat };
