function composePlanOfRecord({ meeting, items, tickets }) {
  const date = meeting.date || new Date().toISOString().slice(0, 10);
  const work = items && items.length ? items : ticketsAsItems(tickets, meeting);
  const human = work.filter((item) => item.route !== "agent");
  const agent = work.filter((item) => item.route === "agent");

  return {
    title: `${meeting.meetingTitle}: plan of record (${date})`,
    executiveSummary: composeSummary(meeting, human, agent),
    context: meeting.transcript || "",
    decisions: work.map((item) => composeDecision(item)),
    actionPlan: composeActionPlan(human, agent),
    risks: composeRisks(agent, work),
    deferred: composeDeferred(work),
  };
}

function renderPlanOfRecord({ doc, meeting, tickets, jobId }) {
  const parts = [];

  parts.push(
    `<ac:structured-macro ac:name="info"><ac:rich-text-body><p>` +
      `Generated by meeting-pipeline from <strong>${esc(meeting.meetingTitle)}</strong>` +
      `${meeting.date ? ` (${esc(meeting.date)})` : ""}` +
      `${meeting.attendees?.length ? `, attendees: ${esc(meeting.attendees.join(", "))}` : ""}.` +
      ` This is the plan of record for the meeting, not a transcript dump.` +
      `</p></ac:rich-text-body></ac:structured-macro>`
  );

  parts.push(`<h2>Executive summary</h2>`);
  parts.push(paragraphs(doc.executiveSummary));

  if (doc.context) {
    parts.push(`<h2>Context</h2>`);
    parts.push(paragraphs(doc.context));
  }

  parts.push(`<h2>Decisions</h2>`);
  for (const decision of doc.decisions) {
    parts.push(`<h3>${esc(decision.decision)}</h3>`);
    if (decision.owner) {
      parts.push(`<p><strong>Owner:</strong> ${esc(decision.owner)}</p>`);
    }
    if (decision.route === "agent") {
      parts.push(`<p><strong>Route:</strong> assignable agent</p>`);
    }
    parts.push(`<p><strong>Why:</strong> ${esc(decision.rationale)}</p>`);
    if (decision.dissent) {
      parts.push(
        `<ac:structured-macro ac:name="note"><ac:rich-text-body><p>` +
          `<strong>Recorded dissent:</strong> ${esc(decision.dissent)}` +
          `</p></ac:rich-text-body></ac:structured-macro>`
      );
    }
  }

  parts.push(`<h2>Action plan</h2>`);
  parts.push(paragraphs(doc.actionPlan));
  if (tickets.length > 0) {
    parts.push(`<p><strong>Tracked in Jira:</strong></p><ul>`);
    for (const ticket of tickets) {
      parts.push(
        `<li><ac:structured-macro ac:name="jira">` +
          `<ac:parameter ac:name="key">${esc(ticket.issueKey)}</ac:parameter>` +
          `</ac:structured-macro> ${esc(ticket.summary || "")}</li>`
      );
    }
    parts.push(`</ul>`);
  }

  if (doc.risks.length > 0) {
    parts.push(`<h2>Risks &amp; open questions</h2><ul>`);
    for (const risk of doc.risks) parts.push(`<li>${esc(risk)}</li>`);
    parts.push(`</ul>`);
  }

  if (doc.deferred.length > 0) {
    parts.push(`<h2>Explicitly deferred</h2>`);
    parts.push(`<p>Recorded so the same debate does not restart next month:</p><ul>`);
    for (const item of doc.deferred) parts.push(`<li>${esc(item)}</li>`);
    parts.push(`</ul>`);
  }

  parts.push(`<hr/><p><em>Pipeline job: ${esc(jobId)}</em></p>`);
  return parts.join("\n");
}

function composeSummary(meeting, human, agent) {
  const bits = [];
  bits.push(
    `${meeting.meetingTitle} produced ${human.length + agent.length} tracked item${human.length + agent.length === 1 ? "" : "s"}.`
  );
  if (human.length) {
    bits.push(
      human
        .map((item) => (item.owner ? `${item.owner} will ${uncapitalize(item.summary)}` : item.summary))
        .join(". ") + "."
    );
  }
  if (agent.length) {
    bits.push(
      `${agent.length} item${agent.length === 1 ? " is" : "s are"} labeled assign-to-agent and still need a recommendation: ` +
        `${agent.map((item) => item.summary).join("; ")}.`
    );
  }
  return bits.join(" ");
}

function composeDecision(item) {
  const owner = item.owner || "";
  const decision = owner ? `${owner} will ${uncapitalize(item.summary)}.` : item.summary;
  return {
    decision,
    owner,
    route: item.route || "human",
    rationale: item.detail || item.summary,
    dissent: extractDissent(item.detail || ""),
  };
}

function composeActionPlan(human, agent) {
  const parts = [];
  if (human.length) {
    parts.push(
      human
        .map((item) => {
          const who = item.owner ? `${item.owner}: ` : "";
          return `${who}${item.summary}${item.detail ? ` — ${item.detail}` : ""}`;
        })
        .join("\n\n")
    );
  }
  if (agent.length) {
    parts.push(
      "These stay parked for an assignable agent (Meeting Pipeline, Copilot, or another custom agent) until someone moves them to Approved for Agent:\n\n" +
        agent.map((item) => item.summary).join("\n\n")
    );
  }
  return parts.join("\n\n");
}

function composeRisks(agent, work) {
  const risks = [];
  for (const item of agent) {
    risks.push(`${item.summary} is still an open recommendation, not an implementation commitment.`);
  }
  for (const item of work) {
    if (!item.owner && item.route !== "agent") {
      risks.push(`${item.summary} has no named owner from the meeting.`);
    }
  }
  return risks;
}

function composeDeferred(work) {
  return work
    .filter((item) => /parked|defer|later|not pursued|symptom/i.test(item.detail || ""))
    .map((item) => item.detail || item.summary);
}

function ticketsAsItems(tickets, meeting) {
  if (tickets.length) {
    return tickets.map((ticket) => ({
      summary: ticket.summary || meeting.meetingTitle,
      detail: ticket.detail || "",
      owner: ticket.owner || "",
      route: ticket.route || "human",
    }));
  }
  return [
    {
      summary: meeting.meetingTitle,
      detail: meeting.transcript || "",
      owner: "",
      route: "human",
    },
  ];
}

function extractDissent(detail) {
  const match = detail.match(/([^.]*(?:dissent|treats a symptom|disagree)[^.]*)\.?/i);
  return match ? match[1].trim() : "";
}

function uncapitalize(text) {
  const value = String(text || "");
  if (!value) return value;
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function paragraphs(text) {
  return String(text)
    .split(/\n\n+/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => `<p>${esc(p)}</p>`)
    .join("\n");
}

function esc(text) {
  return String(text)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

module.exports = { composePlanOfRecord, renderPlanOfRecord };
